version: '3'
services:
  db-microservices:
    container_name: db-microservices
    image: postgres:15.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_microservices
      POSTGRES_USER: db_user_demo
      POSTGRES_PASSWORD: dlpY&2z%0wm#uG%s
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431