FROM amazoncorretto:17-alpine
COPY target/products-service-0.0.1-SNAPSHOT.jar product-service.jar
ENTRYPOINT [ "java", "-jar", "product-service.jar" ]

# FROM maven:3.9.3-eclipse-temurin-11-focal AS build 
# COPY src /home/app/src
# COPY pom.xml /home/app
# RUN mvn -f /home/app/pom.xml clean package -DskipTests

# FROM amazoncorretto:17-alpine
# COPY --from=build home/app/target/products-service-0.0.1-SNAPSHOT.jar product-service.jar
# ENTRYPOINT ["java", "-jar", "product-service.jar"]